### ISSUE TITLE
IDF版本问题

### ISSUE THREAD

**Issue by herexiong** [chaochaofeng/timer_epaper#1]
请问一下您使用的是什么版本的IDF，4.4.7报错，您使用的是ESP32的哪个型号

**Comment by chaochaofeng** [comment]
idf是4.4.3版本
用的是esp32  `idf.py set-target=esp32`

**Comment by herexiong** [comment]
谢谢，因为我手里只有C3，因为SPI原因会一直重启，我再折腾一下

**Comment by herexiong** [comment]
成功运行了，一直以为是驱动或者电路的问题，没想到真的是墨水屏老化了。感谢

**Comment by chaochaofeng** [comment]
我感觉esp3c3比esp32好用，，就是gpio少了些；我用esp32老出现一些莫名其妙的问题
